version: "3.7"

volumes:
  portainer_data:    
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: ./binding/mariadb_data
      o: bind     

services:
  node:
    container_name: node-tech
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./:/server

  mariadb:
    container_name: mariadb
    image: mariadb:10.5.8  
    volumes:
      - ./binding/mariadb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mariadb
    volumes:
      - "/sessions"    
  
